/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FOI;

import Data_Base.DATA_BASE;
import Data_Base.Parameter;
import Data_Base.ResultSetTableModel;
import java.sql.ResultSet;



public final class receipt extends javax.swing.JFrame {
    ResultSet rs;
    DATA_BASE db;
    
    public static String st="2",st1="5",st2="7";
    
   
    /**
     * Creates new form receipt
     */
    public receipt() {
        db = new DATA_BASE(Parameter.HOST_DB, Parameter.USERNAME_DB, Parameter.PASSWORD_DB, 
                Parameter.IPHOST, Parameter.PORT);
        initComponents();
        importer();
        //date();
    }
    
     public static void set_st(String st1){
        st = st1;
        javax.swing.JOptionPane.showMessageDialog(null,st);
    }
     public static void set_st1(String ttl1){
         //ttl1="100";
        //javax.swing.JOptionPane.showMessageDialog(null,st1);
        st1 = ttl1;
    }
     public static void set_st2(String cas1){
         //cas1="20";
        //javax.swing.JOptionPane.showMessageDialog(null,st2);
        st2 = cas1;
     }
   
   /*
     public void importer() {
        String colon[] = {"id","num_invoice","code_product","reference","sales_price","stock_out","subtotal"};
        rs = db.fcSelectCommand(colon, "sales", "num_invoice='" + invoice_num.getText() + "'");
        table_sale.setModel(new ResultSetTableModel(rs));
    }
    */
    
     public void importer() {
         //String st;
       String colon[] = {"num_invoice","code_product","reference","sales_price","stock_out","subtotal"};
       //st = cashier.invoice_num.getText();
        rs = db.fcSelectCommand(colon, "sales", "num_invoice='" + st + "'");
        //rs = db.fcSelectCommand(colon, "sales", "num_invoice=' '");
        table_Print.setModel(new ResultSetTableModel(rs));
        /*
        lbltotal.setText(cashier.total_Rp2.getText());
        lblcash.setText(cashier.txt_cash.getText());
        */
        
        lbltotal.setText(st1);
        lblcash.setText(st2);
        
        payafter();
    }
     
     /*public void date(){
         
        lbld.setText(cashier.lbl1.getText());
        lblh.setText(cashier.lbl2.getText());
    }*/

    public void payafter() {
        /*
        double a = Integer.parseInt(cashier.total_Rp2.getText());
        double b = Integer.parseInt(cashier.txt_cash.getText());
        */
        double a;
        double b;
        try{
            a = Double.parseDouble(st1);
            b = Double.parseDouble(st2);   
        }catch(ArithmeticException e){
            javax.swing.JOptionPane.showMessageDialog(null,"Errrrrrrror");
            a=0;
            b=0;
        }
        
        double c = b - a;
        lblpaid.setText(Integer.toString((int) c));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Print = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblpaid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblh = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblcash = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Receipt");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 10, 120, 55);

        table_Print.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_invoice", "code_product", "reference", "sales_price", "stock_out", "subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_PrintMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Print);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 600, 100);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 240, 140, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 290, 140, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Paid Later:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 350, 110, 40);

        lblpaid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblpaid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpaid.setText("xx");
        lblpaid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblpaid);
        lblpaid.setBounds(400, 350, 150, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Cash:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 300, 60, 30);

        lblh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(lblh);
        lblh.setBounds(320, 70, 230, 40);

        lbltotal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotal.setText("xx");
        jPanel1.add(lbltotal);
        lbltotal.setBounds(400, 250, 150, 40);

        lblcash.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblcash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcash.setText("xx");
        jPanel1.add(lblcash);
        lblcash.setBounds(400, 300, 150, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Total:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 250, 60, 40);

        lbld.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(lbld);
        lbld.setBounds(70, 70, 220, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_PrintMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_PrintMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.printComponents(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cashier C = new cashier();
        C.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new receipt().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcash;
    private javax.swing.JLabel lbld;
    private javax.swing.JLabel lblh;
    private javax.swing.JLabel lblpaid;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable table_Print;
    // End of variables declaration//GEN-END:variables
}
